name: stateless
description: A stateless stateful state management package that is not stateless.
version: 0.1.0
repository: https://github.com/wolfenrain/stateless

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
